// Every code the SDK can surface as a WorkflowValidationError or an ApplicationFailure type.
// The map is frozen so hosts can rely on the values; dynamic wflow importer codes keep the
// `UNSUPPORTED_WFLOW_<FEATURE>` prefix and are intentionally not enumerated.
export const ERROR_CODES = Object.freeze({
  // Client and authorization
  FORBIDDEN: "FORBIDDEN",
  WORKFLOW_NOT_FOUND: "WORKFLOW_NOT_FOUND",
  // Input and definition validation
  INPUT_TOO_COMPLEX: "INPUT_TOO_COMPLEX",
  CYCLIC_INPUT: "CYCLIC_INPUT",
  NON_JSON_INPUT: "NON_JSON_INPUT",
  INPUT_TOO_LARGE: "INPUT_TOO_LARGE",
  DUPLICATE_NODE_ID: "DUPLICATE_NODE_ID",
  TOO_MANY_NODES: "TOO_MANY_NODES",
  CONCURRENT_VARIABLE_WRITE: "CONCURRENT_VARIABLE_WRITE",
  RESUBMIT_REQUIRES_TASK: "RESUBMIT_REQUIRES_TASK",
  DUPLICATE_FIELD: "DUPLICATE_FIELD",
  FIELD_NOT_WRITABLE: "FIELD_NOT_WRITABLE",
  REQUIRED_FIELD: "REQUIRED_FIELD",
  INVALID_FIELD_TYPE: "INVALID_FIELD_TYPE",
  INVALID_FIELD_LENGTH: "INVALID_FIELD_LENGTH",
  INVALID_FIELD_RANGE: "INVALID_FIELD_RANGE",
  INVALID_FIELD_PATTERN: "INVALID_FIELD_PATTERN",
  DEFINITION_VERSION_MISMATCH: "DEFINITION_VERSION_MISMATCH",
  // Scripts and expressions
  SCRIPT_REJECTED: "SCRIPT_REJECTED",
  SCRIPT_EXECUTION_FAILED: "SCRIPT_EXECUTION_FAILED",
  SCRIPT_BUDGET_EXCEEDED: "SCRIPT_BUDGET_EXCEEDED",
  ORDER_REQUIRES_NUMBERS: "ORDER_REQUIRES_NUMBERS",
  MISSING_VARIABLE: "MISSING_VARIABLE",
  // Engine and command handling
  STEP_LIMIT_REACHED: "STEP_LIMIT_REACHED",
  TENANT_MISMATCH: "TENANT_MISMATCH",
  REQUEST_ID_CONFLICT: "REQUEST_ID_CONFLICT",
  COMMAND_LIMIT_REACHED: "COMMAND_LIMIT_REACHED",
  INSTANCE_CLOSED: "INSTANCE_CLOSED",
  INSTANCE_RETURNING: "INSTANCE_RETURNING",
  INSTANCE_MISMATCH: "INSTANCE_MISMATCH",
  INSTANCE_SUSPENDED: "INSTANCE_SUSPENDED",
  INVALID_RETURN_TARGET: "INVALID_RETURN_TARGET",
  RETURN_FORBIDDEN: "RETURN_FORBIDDEN",
  WITHDRAW_FORBIDDEN: "WITHDRAW_FORBIDDEN",
  INVALID_COMMAND: "INVALID_COMMAND",
  INVALID_JUMP_TARGET: "INVALID_JUMP_TARGET",
  // Lifecycle and history management
  INSTANCE_ALREADY_EXISTS: "INSTANCE_ALREADY_EXISTS",
  RESUME_STATE_TOO_LARGE: "RESUME_STATE_TOO_LARGE",
  // Definition migration (controlled: pause -> migrate -> resume)
  MIGRATION_REQUIRES_SUSPENDED: "MIGRATION_REQUIRES_SUSPENDED",
  MIGRATION_REQUIRES_IDLE: "MIGRATION_REQUIRES_IDLE",
  MIGRATION_REQUIRES_TOP_LEVEL: "MIGRATION_REQUIRES_TOP_LEVEL",
  MIGRATION_INVALID_TARGET: "MIGRATION_INVALID_TARGET",
  MIGRATION_TARGET_MISSING: "MIGRATION_TARGET_MISSING",
  // Human tasks
  TASK_NOT_ACTIVE: "TASK_NOT_ACTIVE",
  TASK_CLOSED: "TASK_CLOSED",
  RETURN_REQUIRES_WORKFLOW: "RETURN_REQUIRES_WORKFLOW",
  INVALID_ASSIGNEE: "INVALID_ASSIGNEE",
  NOT_TASK_ASSIGNEE: "NOT_TASK_ASSIGNEE",
  CANNOT_CLAIM: "CANNOT_CLAIM",
  TRANSFER_DISABLED: "TRANSFER_DISABLED",
  ADD_ASSIGNEE_DISABLED: "ADD_ASSIGNEE_DISABLED",
  BEFORE_ADD_FORBIDDEN: "BEFORE_ADD_FORBIDDEN",
  TOO_MANY_ASSIGNEES: "TOO_MANY_ASSIGNEES",
  INVALID_TASK_ACTION: "INVALID_TASK_ACTION",
  SIGNATURE_REQUIRED: "SIGNATURE_REQUIRED",
  NO_ASSIGNEES: "NO_ASSIGNEES",
  // Waits, gateways and subprocesses
  WAIT_NOT_ACTIVE: "WAIT_NOT_ACTIVE",
  WAIT_TIMEOUT: "WAIT_TIMEOUT",
  LOOP_LIMIT_REACHED: "LOOP_LIMIT_REACHED",
  FOREACH_REQUIRES_ARRAY: "FOREACH_REQUIRES_ARRAY",
  FOREACH_LIMIT_REACHED: "FOREACH_LIMIT_REACHED",
  RECURSIVE_CHILD_DEFINITION: "RECURSIVE_CHILD_DEFINITION",
  CHILD_NOT_COMPLETED: "CHILD_NOT_COMPLETED",
  // wflow importer
  INVALID_WFLOW_OBJECT: "INVALID_WFLOW_OBJECT",
  INVALID_WFLOW_STRING: "INVALID_WFLOW_STRING",
  INVALID_WFLOW_DURATION: "INVALID_WFLOW_DURATION",
  INVALID_WFLOW_DATE_TIME: "INVALID_WFLOW_DATE_TIME",
  INVALID_WFLOW_RANGE: "INVALID_WFLOW_RANGE",
  INVALID_WFLOW_BRANCHES: "INVALID_WFLOW_BRANCHES",
  EMPTY_WFLOW_CONDITION: "EMPTY_WFLOW_CONDITION",
  DANGLING_WFLOW_LINK: "DANGLING_WFLOW_LINK",
  CYCLIC_WFLOW_LINK: "CYCLIC_WFLOW_LINK",
  UNSUPPORTED_WFLOW_EVENT_TYPE: "UNSUPPORTED_WFLOW_EVENT_TYPE",
  // Host adapter and delivery failures (ApplicationFailure types)
  INVALID_ADAPTER_PAYLOAD: "INVALID_ADAPTER_PAYLOAD",
  ADAPTER_FAILED: "ADAPTER_FAILED",
  UNKNOWN_ACTION: "UNKNOWN_ACTION",
  UNKNOWN_NODE_KIND: "UNKNOWN_NODE_KIND",
  INTEGRATION_NOT_SUPPORTED: "INTEGRATION_NOT_SUPPORTED",
  INVALID_WORKFLOW_INPUT: "INVALID_WORKFLOW_INPUT",
  IDENTITY_MISMATCH: "IDENTITY_MISMATCH",
  EXECUTION_FAILED: "EXECUTION_FAILED",
  EVENT_DELIVERY_FAILED: "EVENT_DELIVERY_FAILED",
});
export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];

export class WorkflowValidationError extends Error {
  constructor(public readonly code: ErrorCode | (string & {})) { super(code); this.name = "WorkflowValidationError"; }
}

/** Options for {@link AdapterError}. */
export interface AdapterErrorOptions {
  /** Defaults to true, matching today's retryable treatment of unclassified adapter failures. */
  retryable?: boolean;
  cause?: unknown;
}

/**
 * Host adapters throw this to surface a safe error code and an explicit retry intent. The engine
 * maps it to an ApplicationFailure that keeps the code but never the host message or stack.
 */
export class AdapterError extends Error {
  readonly retryable?: boolean;
  constructor(readonly code: string, options: AdapterErrorOptions = {}) {
    super(code, options.cause === undefined ? undefined : { cause: options.cause });
    this.name = "AdapterError";
    this.retryable = options.retryable;
  }
}
